/**
 * Generates the `_headers` file Cloudflare Pages serves alongside the site,
 * and exports the policy so Azure's config can carry the same one.
 *
 * The Content-Security-Policy is derived from the built pages: every inline
 * `<script>` and `<style>` body in `dist/` is hashed and listed, so the policy
 * cannot drift out of step with the markup.
 *
 * The site talks to exactly three places: itself (`/api/drive`), Google Fonts
 * for the stylesheet, and Google's font host for the files it names.
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
const INLINE_STYLE = /<style[^>]*>([\s\S]*?)<\/style>/gi;

const hashOf = (body) => `'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`;

function htmlFiles(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) htmlFiles(full, out);
    else if (entry.isFile() && full.endsWith('.html')) out.push(full);
  }
  return out.sort();
}

/**
 * @param {string} dist the built site
 * @returns {string} the policy, as a single header value
 */
export function contentSecurityPolicy(dist) {
  const scripts = new Set();
  const styles = new Set();

  for (const file of htmlFiles(dist)) {
    const source = fs.readFileSync(file, 'utf8');
    for (const [, body] of source.matchAll(INLINE_SCRIPT)) scripts.add(hashOf(body));
    for (const [, body] of source.matchAll(INLINE_STYLE)) styles.add(hashOf(body));
  }

  return [
    "default-src 'none'",
    ["script-src 'self'", ...[...scripts].sort()].join(' '),
    ["style-src 'self' https://fonts.googleapis.com", ...[...styles].sort()].join(' '),
    'font-src https://fonts.gstatic.com',
    "connect-src 'self'",
    "img-src 'self' data:",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join('; ');
}

/** @type {Record<string, string>} */
export const SECURITY_HEADERS = {
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

/**
 * @param {string} dist the built site
 * @returns {string} the complete `_headers` text
 */
export function generateHeaders(dist) {
  const csp = contentSecurityPolicy(dist);
  return [
    '# Generated by scripts/gen-headers.mjs. Do not edit by hand.',
    '/*',
    `  Content-Security-Policy: ${csp}`,
    ...Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`),
    '',
  ].join('\n');
}
